// DO NOT EDIT
// This file was code-generated by  version
// It is expected that this file will be re-generated and overwitten to
// adapt to changes in the OpenAPI spec that was used to generate it

package category

import (
	_ "embed"
)

// Category
type Category struct {
	ID   string `gorm:"primaryKey;unique;type:uuid;default:uuid_generate_v4();" json:"id"`
	Name string `gorm:"not null" json:"name"`
}

// Create Category
type CreateCategoryRequest struct {
	Name string `json:"name"`
	Upc  string `json:"upc"`
}

// HTTPError defines model for HTTPError.
type HTTPError struct {
	Message *string `json:"message,omitempty"`
}

// BadRequestError defines model for BadRequestError.
type BadRequestError HTTPError

// ForbiddenError defines model for ForbiddenError.
type ForbiddenError HTTPError

// InternalServerError defines model for InternalServerError.
type InternalServerError HTTPError

// NotFoundError defines model for NotFoundError.
type NotFoundError HTTPError

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError HTTPError

// Create Category
type CreateCategory CreateCategoryRequest

// Category
type UpdateCategory Category
