// DO NOT EDIT
// This file was code-generated by  version
// It is expected that this file will be re-generated and overwitten to
// adapt to changes in the OpenAPI spec that was used to generate it

package location

import (
	_ "embed"
	"time"
	"github.com/jdotw/stock/pkg/transaction"
)

// Create Location
type CreateLocationRequest struct {
	Name string `json:"name"`
}

// HTTPError defines model for HTTPError.
type HTTPError struct {
	Message *string `json:"message,omitempty"`
}

// Location
type Location struct {
	ID           string                 `gorm:"primaryKey;unique;type:uuid;default:uuid_generate_v4();" json:"id"`
	Name         string                 `gorm:"not null" json:"name"`
	Transactions *[]transaction.Transaction `json:"transactions,omitempty"`
}

// BadRequestError defines model for BadRequestError.
type BadRequestError HTTPError

// ForbiddenError defines model for ForbiddenError.
type ForbiddenError HTTPError

// InternalServerError defines model for InternalServerError.
type InternalServerError HTTPError

// NotFoundError defines model for NotFoundError.
type NotFoundError HTTPError

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError HTTPError

// Create Location
type CreateLocation CreateLocationRequest

// Location
type UpdateLocation Location
