openapi: "3.0.2"
info:
  title: Stock API
  version: "1.0"
servers:
  - url: https://api.server.test/v1
paths:
  #
  # Categories
  #
  /categories:
    get:
      tags:
        - Category
      summary: Get all Categories
      description: Get all Categories
      operationId: GetCategories
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Category"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "500":
          $ref: "#/components/responses/InternalServerError"
    post:
      tags:
        - Category
      summary: Create Category
      description: Create Category
      operationId: CreateCategory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCategoryRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "403":
          $ref: "#/components/responses/ForbiddenError"
        "500":
          $ref: "#/components/responses/InternalServerError"
  /categories/{category_id}:
    get:
      tags:
        - Category
      summary: Get Category
      description: Get Category
      operationId: GetCategory
      parameters:
        - $ref: "#/components/parameters/CategoryID"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "500":
          $ref: "#/components/responses/InternalServerError"
    patch:
      tags:
        - Category
      summary: Update Category
      description: Update Category
      operationId: UpdateCategory
      parameters:
        - $ref: "#/components/parameters/CategoryID"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        "400":
          $ref: "#/components/responses/BadRequestError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "403":
          $ref: "#/components/responses/ForbiddenError"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "500":
          $ref: "#/components/responses/InternalServerError"
    delete:
      tags:
        - Category
      summary: Delete a Category
      description: Delete a Category
      operationId: DeleteCategory
      parameters:
        - $ref: "#/components/parameters/CategoryID"
      responses:
        "200":
          description: OK
        "400":
          $ref: "#/components/responses/BadRequestError"
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "403":
          $ref: "#/components/responses/ForbiddenError"
        "404":
          $ref: "#/components/responses/NotFoundError"
        "500":
          $ref: "#/components/responses/InternalServerError"
components:
  schemas:
    # Objects
    Category:
      description: Category
      type: object
      properties:
        id:
          type: string
          x-oapi-codegen-extra-tags:
            gorm: "primaryKey;unique;type:uuid;default:uuid_generate_v4();"
        name:
          type: string
          x-oapi-codegen-extra-tags:
            gorm: "not null"
    CreateCategoryRequest:
      description: "Create Syrup Category"
      type: object
      properties:
        name:
          type: string
    # Errors
    HTTPError:
      type: object
      properties:
        message:
          type: string
  parameters:
    CategoryID:
      name: category_id
      in: path
      required: true
      style: simple
      explode: false
      schema:
        type: string
  responses:
    HTTPError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/HTTPError"
    BadRequestError:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/HTTPError"
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/HTTPError"
    ForbiddenError:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/HTTPError"
    NotFoundError:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/HTTPError"
    TooManyRequestsError:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/HTTPError"
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/HTTPError"
