version: "3.9"
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yaml
  # db:
  #   image: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
  #     - ./db/init:/docker-entrypoint-initdb.d
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: postgres
  #   command:
  #     [
  #       "postgres",
  #       "-c",
  #       "log_statement=none",
  #       "-c",
  #       "max_connections=1000",
  #       "-c",
  #       "shared_buffers=512MB",
  #     ]
  redpanda:
    image: docker.redpanda.com/vectorized/redpanda:latest
    container_name: redpanda-1
    command:
      - redpanda
      - start
      - --smp
      - "1"
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - "0"
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr
      - PLAINTEXT://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
      - --advertise-pandaproxy-addr
      - PLAINTEXT://redpanda:28082,OUTSIDE://localhost:8082
    ports:
      - 8081:8081
      - 8082:8082
      - 9092:9092
      - 28082:28082
      - 29092:29092
  cache:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache-data:/data

  # influxdb:
  #   image: influxdb:latest
  #   container_name: influxdb2
  #   volumes:
  #     - ./influxdb2/etc:/etc/influxdb2
  #     - influxdb2:/var/lib/influxdb2:rw
  #   # env_file:
  #   #   - influx.setup.env
  #   # entrypoint: ["./entrypoint.sh"]
  #   ports:
  #     - 8086:8086
  #   restart: unless-stopped

  # influxdb:
  #   restart: unless-stopped
  #   container_name: influxdb
  #   image: influxdb:1.8
  #   volumes:
  #     - ./influxdb/etc:/etc/influxdb
  #     - influxdb-lib:/var/lib/influxdb
  #   env_file:
  #     - ./.env
  #   ports:
  #     - 8083:8083
  #     - 8086:8086
  #     - 8088:8088
  #   privileged: true

  grafana:
    image: grafana/grafana:latest
    # networks:
    #   - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana

  # grafana:
  #   image: grafana/grafana:7.5.7
  #   ports:
  #     - 3000:3000
  #   restart: unless-stopped
  #   volumes:
  #     - grafana-data:/var/lib/grafana

volumes:
  prometheus-data:
  db-data:
  cache-data:
    driver: local
  influxdb2:
  # influxdb-lib:
  grafana-data:
